name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'   # Subah 11 baje IST (UTC+5:30)
    - cron: '30 17 * * *'  # Raat 11 baje IST (UTC+5:30)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add newline and commit
        run: |
          echo "" >> README.md
          git config user.email "ag161158@gmail.com"
          git config user.name "Aditya"
          git add README.md
          git commit -m "daily commit: $(date '+%Y-%m-%d')"
          git push
